// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function calsPercent(score, max) {
  return score / max * 100.0;
}

var result = calsPercent(60, 75);

console.log(" Подделка результатов составляет " + result + " ");

var person = 60;

exports.person = person;
exports.calsPercent = calsPercent;
exports.result = result;
/* result Not a pure module */
