// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var mySize = /* Medium */1;

var otherSize = /* Large */2;

exports.mySize = mySize;
exports.otherSize = otherSize;
/* No side effect */
